## Add L/R to ground truth data

In [1]:
import pandas as pd
import re

# Load the Excel file
df = pd.read_excel("ground_truth_measurements.xlsx")  # Update with your actual file path

# Extract "Side" from Filename
def extract_side(filename):
    if "left_eye" in filename:
        return "L"
    elif "right_eye" in filename:
        return "R"
    else:
        return None

# Extract frame number from Filename using regex
def extract_frame(filename):
    match = re.search(r'_(\d+)_', filename)
    return int(match.group(1)) if match else None

# Extract name (prefix before frame number)
def extract_name(filename):
    match = re.match(r'([a-zA-Z]+)_\d+_', filename)
    return match.group(1) if match else None

# Apply all extractions
df["Side"] = df["Filename"].apply(extract_side)
df["frame"] = df["Filename"].apply(extract_frame)
df["name"] = df["Filename"].apply(extract_name)

# Save the updated DataFrame
df.to_csv("new_ground_truth_measurements.csv", index=False)

print("Updated file saved as 'new_ground_truth_measurements.csv'")

Updated file saved as 'new_ground_truth_measurements.csv'

In [2]:
gt_df = pd.read_csv("new_ground_truth_measurements.csv")

In [3]:
gt_df.head()

,Filename,Class,vpf_expected,mrd1_expected,vpf,mrd1,Side,frame,name
0,avneesh_0189_left_eye.jpg,Partial,2.06,0.00,NaN,NaN,L,189,avneesh
1,avneesh_0189_right_eye.jpg,Partial,1.41,0.00,NaN,NaN,R,189,avneesh
2,avneesh_0204_left_eye.jpg,Partial,7.43,1.99,NaN,NaN,L,204,avneesh
3,avneesh_0204_right_eye.jpg,Partial,7.55,1.65,NaN,NaN,R,204,avneesh
4,avneesh_0207_left_eye.jpg,Partial,7.63,1.65,NaN,NaN,L,207,avneesh

In [4]:
gt_df.drop(columns=["Class"], inplace=True)
gt_df.head()

,Filename,vpf_expected,mrd1_expected,vpf,mrd1,Side,frame,name
0,avneesh_0189_left_eye.jpg,2.06,0.00,NaN,NaN,L,189,avneesh
1,avneesh_0189_right_eye.jpg,1.41,0.00,NaN,NaN,R,189,avneesh
2,avneesh_0204_left_eye.jpg,7.43,1.99,NaN,NaN,L,204,avneesh
3,avneesh_0204_right_eye.jpg,7.55,1.65,NaN,NaN,R,204,avneesh
4,avneesh_0207_left_eye.jpg,7.63,1.65,NaN,NaN,L,207,avneesh

In [6]:
# Save the updated DataFrame
gt_df.to_csv("filename_refactored_ground_truth_measurements.csv", index=False)

## Format GUI Measured Data

In [7]:
# av_df = pd.read_excel("avneesh_estimates.xlsx")
# av_df.head()

   timestamp  frame   left_vph  left_mrd1  right_vph  right_mrd1
0   0.035738      0  25.079872  13.152946  24.020824   12.165525
1   0.365221      1  25.079872  13.152946  26.076810   13.038405
2   0.645133      2  25.079872  13.152946  26.076810   13.038405
3   0.934376      3  25.179357  13.152946  24.000000   12.369317
4   1.271017      4  24.083189  12.165525  25.079872   13.038405

In [8]:
# av_df['name'] = "avneesh"
# av_df.head()

   timestamp  frame   left_vph  left_mrd1  right_vph  right_mrd1     name
0   0.035738      0  25.079872  13.152946  24.020824   12.165525  avneesh
1   0.365221      1  25.079872  13.152946  26.076810   13.038405  avneesh
2   0.645133      2  25.079872  13.152946  26.076810   13.038405  avneesh
3   0.934376      3  25.179357  13.152946  24.000000   12.369317  avneesh
4   1.271017      4  24.083189  12.165525  25.079872   13.038405  avneesh

In [ ]:
# ethan_df = pd.read_excel("ethan_estimates.xlsx")
# ethan_df.head()

In [ ]:
# ethan_df['name'] = "ethan"
# ethan_df.head()

In [ ]:
# Combine the two dataframes
combined_df = pd.concat([av_df, ethan_df], ignore_index=True)
# combined_df.head()

In [12]:
# Save the combined dataframe
# combined_df.to_csv("combined_measurements.csv", index=False)

## Fill in measurements

In [9]:
# load estimated measurements
combined_df = pd.read_csv("combined_measurements.csv")
combined_df.head()

   timestamp  frame   left_vph  left_mrd1  right_vph  right_mrd1     name
0   0.035738      0  25.079872  13.152946  24.020824   12.165525  avneesh
1   0.365221      1  25.079872  13.152946  26.076810   13.038405  avneesh
2   0.645133      2  25.079872  13.152946  26.076810   13.038405  avneesh
3   0.934376      3  25.179357  13.152946  24.000000   12.369317  avneesh
4   1.271017      4  24.083189  12.165525  25.079872   13.038405  avneesh

In [10]:
# load ground truth measurements
gt_df = pd.read_csv("filename_refactored_ground_truth_measurements.csv")
gt_df.head()

,Filename,vpf_expected,mrd1_expected,vpf,mrd1,Side,frame,name
0,avneesh_0189_left_eye.jpg,2.06,0.00,NaN,NaN,L,189,avneesh
1,avneesh_0189_right_eye.jpg,1.41,0.00,NaN,NaN,R,189,avneesh
2,avneesh_0204_left_eye.jpg,7.43,1.99,NaN,NaN,L,204,avneesh
3,avneesh_0204_right_eye.jpg,7.55,1.65,NaN,NaN,R,204,avneesh
4,avneesh_0207_left_eye.jpg,7.63,1.65,NaN,NaN,L,207,avneesh

## Fill in vpf and mrd1 measurements

In [11]:
import pandas as pd

# Load files (replace with actual paths if needed)
ground_truth_df = pd.read_csv("filename_refactored_ground_truth_measurements.csv")  # has NaNs
measured_df = pd.read_csv("combined_measurements.csv")  # has full measurements

# Merge on 'name' and 'frame'
merged = pd.merge(ground_truth_df, measured_df, on=["name", "frame"], how="left")

# Define fill logic strictly based on correct Side
def fill_vpf(row):
    if row["Side"] == "L":
        return row["left_vph"]
    elif row["Side"] == "R":
        return row["right_vph"]
    return None

def fill_mrd1(row):
    if row["Side"] == "L":
        return row["left_mrd1"]
    elif row["Side"] == "R":
        return row["right_mrd1"]
    return None

# Only update vpf/mrd1 if they're NaN (preserve existing values)
merged["vpf"] = merged.apply(lambda row: fill_vpf(row) if pd.isna(row["vpf"]) else row["vpf"], axis=1)
merged["mrd1"] = merged.apply(lambda row: fill_mrd1(row) if pd.isna(row["mrd1"]) else row["mrd1"], axis=1)

# Drop the extra columns used in merging if you want to keep the original structure
final_df = merged[ground_truth_df.columns]

# Save final result
final_df.to_csv("ground_truth_filled.csv", index=False)
print("Saved to 'ground_truth_filled.csv'")

Saved to 'ground_truth_filled.csv'

## Investigate ground truth filled

In [12]:
df = pd.read_csv("ground_truth_filled.csv")
df.head()

,Filename,vpf_expected,mrd1_expected,vpf,mrd1,Side,frame,name
0,avneesh_0189_left_eye.jpg,2.06,0.00,26.172505,13.152946,L,189,avneesh
1,avneesh_0189_right_eye.jpg,1.41,0.00,25.000000,13.341664,R,189,avneesh
2,avneesh_0204_left_eye.jpg,7.43,1.99,27.166155,14.317821,L,204,avneesh
3,avneesh_0204_right_eye.jpg,7.55,1.65,27.018512,13.152946,R,204,avneesh
4,avneesh_0207_left_eye.jpg,7.63,1.65,26.076810,14.560220,L,207,avneesh

## todo: fix missing data

## Look at missing data

In [2]:
import pandas as pd

In [3]:
av_df = pd.read_excel("avneesh_estimates.xlsx")
av_df.head()

   timestamp  frame   left_vph  left_mrd1  right_vph  right_mrd1
0   0.035738      0  25.079872  13.152946  24.020824   12.165525
1   0.365221      1  25.079872  13.152946  26.076810   13.038405
2   0.645133      2  25.079872  13.152946  26.076810   13.038405
3   0.934376      3  25.179357  13.152946  24.000000   12.369317
4   1.271017      4  24.083189  12.165525  25.079872   13.038405

In [4]:
av_df[av_df['frame'] == 766]

Empty DataFrame
Columns: [timestamp, frame, left_vph, left_mrd1, right_vph, right_mrd1]
Index: []

In [5]:
av_df['frame'].describe()

count    751.000000
mean     375.000000
std      216.939316
min        0.000000
25%      187.500000
50%      375.000000
75%      562.500000
max      750.000000
Name: frame, dtype: float64

In [6]:
av_df.head()

   timestamp  frame   left_vph  left_mrd1  right_vph  right_mrd1
0   0.035738      0  25.079872  13.152946  24.020824   12.165525
1   0.365221      1  25.079872  13.152946  26.076810   13.038405
2   0.645133      2  25.079872  13.152946  26.076810   13.038405
3   0.934376      3  25.179357  13.152946  24.000000   12.369317
4   1.271017      4  24.083189  12.165525  25.079872   13.038405

## Calculate sampling rate

In [9]:
time_diff = av_df['timestamp'][1] - av_df['timestamp'][0]
time_diff

0.32948303300000004

In [10]:
fps = 1 / time_diff
fps

3.035057650449636

In [11]:
ethan_df = pd.read_excel("ethan_estimates.xlsx")
ethan_df.head()

   timestamp  frame   left_vph  left_mrd1  right_vph  right_mrd1
0   0.109284      0  46.097722  23.000000  44.011362   22.090722
1   0.571409      1  46.097722  22.000000  43.011626   21.095023
2   0.897131      2  44.384682  22.022716  43.000000   21.023796
3   1.214450      3  45.354162  22.022716  42.011903   21.095023
4   1.485063      4  46.097722  22.000000  44.000000   21.000000

In [14]:
ethan_time_diff = ethan_df['timestamp'][1] - ethan_df['timestamp'][0]
ethan_time_diff

0.462124824

In [15]:
ethan_fps = 1 / ethan_time_diff
ethan_fps

2.1639175133340163

## 4/9: The sampling rates are different so the frames don't line up. That is why there is some data missing