### Note: This notebook uses Weights & Biases, which is a tool to streamline model experimentation. You can visit the website here and setup an account: https://wandb.ai

## Import Libraries

In [1]:
import os
import numpy as np
import pandas as pd
from PIL import Image
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
import matplotlib.pyplot as plt
from torchvision.transforms import functional as TF
from skimage.metrics import structural_similarity as ssim
import tifffile

In [2]:
import wandb
!wandb login

wandb: Currently logged in as: joshi-373 (joshi-373-The Ohio State University). Use `wandb login --relogin` to force relogin

## Enable Hardware

In [3]:
device = torch.device('mps' if torch.backends.mps.is_available() else 'cpu')
print('Device available:', device)

Device available: mps

## TODO: Convert Data Augmentation Outputs into Image Inputs for Model

In [4]:
## TODO

## Create Dataset
Note: Ensure a train/validation/test split is created prior to running these cells. See the data_processing.ipynb file.

### Data Path

In [2]:
# Define model data path
model_data_path = "/Users/mihirjoshi/Documents/OSU/2024-2025/Capstone/EyesPy/data/10-30-2024/model_data/" 
# model_data_path = "/Users/mihirjoshi/Documents/OSU/2024-2025/Capstone/EyesPy/data/10-30-2024/model_data/subset/"

# Update these parameters
data_path = model_data_path

train_label =  'Train/'
val_label = 'Validation/'

### Load labels

In [3]:
labels_path = "/Users/mihirjoshi/Documents/OSU/2024-2025/Capstone/EyesPy/data/10-30-2024/class_vpf_labels.xlsx"
df = pd.read_excel(labels_path)
df.head()

            filename class     vpf
0  1599577832838.bmp  Open  11.403
1  1599577832871.bmp  Open  11.530
2  1599577832905.bmp  Open  11.615
3  1599577832938.bmp  Open  11.528
4  1599577832969.bmp  Open  11.359

In [7]:
df[df['class'] == 'Closed'].count()

filename    14
class       14
vpf         14
dtype: int64

In [8]:
df[df['class'] == 'Partial'].count()

filename    39
class       39
vpf         39
dtype: int64

In [9]:
# Convert class names to numbers {open: 0,  partial: 1, closed: 2}
unique_classes = df['class'].unique()
class_mapping = {cls: idx for idx, cls in enumerate(unique_classes)}

df['class'] = df['class'].map(class_mapping)
df.head()

            filename  class     vpf
0  1599577832838.bmp      0  11.403
1  1599577832871.bmp      0  11.530
2  1599577832905.bmp      0  11.615
3  1599577832938.bmp      0  11.528
4  1599577832969.bmp      0  11.359

In [10]:
class EyeDataset(Dataset):
    def __init__(self, directory, dataframe, transform=None):
        self.directory = directory
        self.dataframe = dataframe
        self.transform = transform
        self.filenames = self.__get_valid_filenames()

    def __get_valid_filenames(self):
        # Get all image files in the directory
        all_files = [f for f in os.listdir(self.directory) if f.endswith(('.png', '.jpg', '.jpeg', '.tif', '.bmp'))]
        
        # Filter files that exist in both the directory and the dataframe
        valid_files = [f for f in all_files if f in self.dataframe['filename'].values]
        
        return valid_files

    def __len__(self):
        return len(self.filenames)

    def __getitem__(self, idx):
        filename = self.filenames[idx]
        img_path = os.path.join(self.directory, filename)

        # get corresponding row from dataframe
        row = self.dataframe[self.dataframe['filename'] == filename].iloc[0]

        # Load image
        image = self.__load_image(img_path)

        # Get class and VPF from dataframe
        class_label = row['class']
        vpf = row['vpf']

        return filename, image, class_label, vpf
    
    def __load_image(self, img_path):
        image = Image.open(img_path)
        if self.transform: # Dynamically apply data transformation
            image = self.transform(image)
        return image


# Create a transform to convert the images to PyTorch tensors
transform = transforms.Compose([
    transforms.ToTensor()
])

# Create the dataset for images
train_data = EyeDataset(data_path + train_label, df, transform=transform)
val_data = EyeDataset(data_path + val_label, df, transform=transform)

# Function to create data loader
def create_loader(train_dataset, batch_size):
    torch.manual_seed(0)  # For reproducibility of random numbers in PyTorch
    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)  # Creates a training DataLoader from this Dataset

    return train_loader

train_dataset_size = len(train_data)
print('Number of images in the training dataset:', train_dataset_size)

val_dataset_size = len(val_data)
print('Number of images in the validation dataset:', val_dataset_size)

Number of images in the training dataset: 118
Number of images in the validation dataset: 34

In [9]:
train_data[0][1].shape

torch.Size([1, 1536, 2048])

In [ ]:
total_open = 0
total_partial = 0
total_closed = 0


for data_sample in train_data:
    data_class = data_sample[2]

    if data_class == 0:
        total_open += 1

    elif data_class == 1:
        total_partial += 1

    else:
        total_closed += 1


print(f"Totals: \n  Open: {total_open}\n  Partial: {total_partial}\n  Closed: {total_closed}")

print(f"Percentages: \n  Open: {(total_open/train_dataset_size) * 100}\n  Partial: {(total_partial / train_dataset_size) * 100}\n  Closed: {(total_closed / train_dataset_size) * 100}")

Totals:
  Open: 83
  Partial: 28
  Closed: 7
Percentages:
  Open: 70.33898305084746
  Partial: 23.728813559322035
  Closed: 5.932203389830509

In [18]:
total_open = 0
total_partial = 0
total_closed = 0


for data_sample in val_data:
    data_class = data_sample[2]

    if data_class == 0:
        total_open += 1

    elif data_class == 1:
        total_partial += 1

    else:
        total_closed += 1


print(f"Totals: \n  Open: {total_open}\n  Partial: {total_partial}\n  Closed: {total_closed}")

print(f"Percentages: \n  Open: {(total_open/val_dataset_size) * 100}\n  Partial: {(total_partial / val_dataset_size) * 100}\n  Closed: {(total_closed / val_dataset_size) * 100}")

Totals:
  Open: 24
  Partial: 6
  Closed: 4
Percentages:
  Open: 70.58823529411765
  Partial: 17.647058823529413
  Closed: 11.76470588235294

In [ ]:
# train_data[0][2] == 0

np.True_

In [10]:
# Check if images were loaded correctly
dataset_correct = True

files = os.listdir(data_path + train_label)
image_extensions = ('.jpg', '.jpeg', '.png', '.gif', '.bmp')
image_files = [f for f in files if f.lower().endswith(image_extensions)]
index = 0

for img_idx in range(len(image_files)):
    index = img_idx
    curr_image = image_files[img_idx]

    filename_matches = (df[df['filename'] == curr_image]['filename'] == train_data[img_idx][0]).item()
    class_matches = (df[df['filename'] == curr_image]['class'] == train_data[img_idx][2]).item()
    vpf_matches = (df[df['filename'] == curr_image]['vpf'] == train_data[img_idx][3]).item()

    if not(filename_matches & class_matches & vpf_matches):
        dataset_correct = False
        break

if dataset_correct:
    print("Dataset created correctly!")
else:
    print(f"Uh oh :( the dataset was not correct at: {df.loc[index]}")

Dataset created correctly!

## Define Model Architecture

In [11]:
class ModifiedUNet(nn.Module):
    def __init__(self):
        super(ModifiedUNet, self).__init__()

        # Encoder (Contracting Path)
        self.inc = self.double_conv(1, 64)
        self.down1 = self.down(64, 128)
        self.down2 = self.down(128, 256)
        self.down3 = self.down(256, 512)
        self.down4 = self.down(512, 1024)

        # Decoder (Expanding Path)
        self.up1 = self.up(1024, 512)
        self.up2 = self.up(512, 256)
        self.up3 = self.up(256, 128)
        self.up4 = self.up(128, 64)

        # Final convolution
        self.outc = nn.Conv2d(64, 1, kernel_size=1)

        # Global Average Pooling
        self.gap = nn.AdaptiveAvgPool2d(1)

        # Fully connected layers for final output
        self.fc1 = nn.Linear(2, 64)
        self.fc2 = nn.Linear(64, 1)

    def forward(self, x, class_label):

        # print(f"Input x device: {x.device}, dtype: {x.dtype}")
        # print(f"class_label device: {class_label.device}, dtype: {class_label.dtype}")


        # Encoder
        x1 = self.inc(x)
        x2 = self.down1(x1)
        x3 = self.down2(x2)
        x4 = self.down3(x3)
        x5 = self.down4(x4)

        # Decoder
        x = self.up1(x5)
        x = torch.cat([x, x4], dim=1)
        x = self.up_conv(x.size(1), 512)(x)

        x = self.up2(x)
        x = torch.cat([x, x3], dim=1)
        x = self.up_conv(x.size(1), 256)(x)

        x = self.up3(x)
        x = torch.cat([x, x2], dim=1)
        x = self.up_conv(x.size(1), 128)(x)

        x = self.up4(x)
        x = torch.cat([x, x1], dim=1)
        x = self.up_conv(x.size(1), 64)(x)

        x = self.outc(x)

        # Global Average Pooling
        x = self.gap(x)
        x = x.view(x.size(0), -1)

        # Unsqueeze class_label to make it 2D
        class_label = class_label.unsqueeze(1).float()

        # Concatenate with class label
        x = torch.cat([x, class_label], dim=1)

        # Fully connected layers
        x = F.relu(self.fc1(x))
        x = self.fc2(x)

        return x.squeeze()

    def double_conv(self, in_channels, out_channels):
        return nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1),
            nn.ReLU(inplace=True)
        )

    def down(self, in_channels, out_channels):
        return nn.Sequential(
            nn.MaxPool2d(2),
            self.double_conv(in_channels, out_channels)
        )

    def up(self, in_channels, out_channels):
        return nn.ConvTranspose2d(in_channels, out_channels, kernel_size=2, stride=2)

    def up_conv(self, in_channels, out_channels):
        return self.double_conv(in_channels, out_channels)

## Functions for executing training & validation

### To do: train in batches

In [12]:
# Training and validation loops
def train_epoch(device, model, loader, criterion, optimizer):
    model.train()
    running_loss = 0.0
    
    count = 0
    for _, img, class_name, vpf in loader:

        img = img.to(device=device, dtype=torch.float32)
        # print(img.shape)
        class_name = class_name.to(device=device, dtype=torch.float32)
        # print(class_name.shape)
        
        if torch.backends.mps.is_available():
            # Pytorch only converts MPS tensors to float32
            actual_vpf = vpf.to(device=device, dtype=torch.float32)
        else:
            actual_vpf = vpf.to(device).float()

        optimizer.zero_grad()
        output = model(img, class_name) # model vpf estimation
        loss = criterion(output, actual_vpf) # calculate loss
        loss.backward()
        optimizer.step()
        running_loss += loss.item()

    print(f"batch {count+1}")
    count += 1

    curr_loss = running_loss / len(loader)
    wandb.log({"train_MSE":curr_loss})
    return curr_loss

def validate(device, model, loader, criterion):
    model.eval()
    running_loss = 0.0
    with torch.no_grad():
        for _, img, class_name, vpf in loader:

            img = img.to(device=device, dtype=torch.float32)
            class_name = class_name.to(device=device, dtype=torch.float32)
            
            if torch.backends.mps.is_available():
                # Pytorch only converts MPS tensors to float32
                actual_vpf = vpf.to(device=device, dtype=torch.float32)
            else:
                actual_vpf = vpf.to(device).float()
            
            output = model(img, class_name) # make vpf prediction
            loss = criterion(output, actual_vpf) # calculate loss
            running_loss += loss.item()
        curr_loss = running_loss / len(loader)
        wandb.log({"train_MSE":curr_loss})
    return curr_loss

def training_and_validation(device, num_epochs, model, train_loader, val_loader, criterion, optimizer):
    train_losses = []
    val_losses = []

    for epoch in range(num_epochs):
        train_loss = train_epoch(device, model, train_loader, criterion, optimizer)
        print(f"Epoch {epoch+1}/{num_epochs}, Train Loss: {train_loss:.4f}")
        val_loss = validate(device, model, val_loader, criterion)
        print(f"Epoch {epoch+1}/{num_epochs}, Val Loss: {val_loss:.4f}")
        
        train_losses.append(train_loss)
        val_losses.append(val_loss)
        
        

    # Plotting the loss curves
    plt.figure(figsize=(10, 5))
    plt.plot(range(1, num_epochs+1), train_losses, label='Train Loss')
    plt.plot(range(1, num_epochs+1), val_losses, label='Validation Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training and Validation Loss Curves')
    plt.legend()
    plt.show()

## Define model & hyperparameters & labels

In [13]:
# Initialize the model, loss function, and optimizer
device = torch.device("cpu") #torch.device("mps" if torch.backends.mps.is_available() else "cpu")

# hyperparameters
num_epochs = 20
batch_size = 1
learning_rate = 0.001

model = ModifiedUNet().to(device)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

In [14]:
wandb.init(
    # set wandb project
    project="eyespy-mpd",

    # track hyperparameters
    config={
        "learning_rate": learning_rate,
        "epochs": num_epochs,
        "batch_size": batch_size,
        "loss":"MSE",
        "dataset": "Ethan, Avneesh, Aditi Data",
        "architecture": "Modified UNet"
    }
)

wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: joshi-373 (joshi-373-The Ohio State University). Use `wandb login --relogin` to force relogin

## Initialize Training & Validation Dataloaders

In [15]:
train_loader = create_loader(train_data, batch_size)
val_loader = create_loader(val_data, batch_size)

In [ ]:
training_and_validation(device, num_epochs, model, train_loader, val_loader, criterion, optimizer)

/Users/mihirjoshi/anaconda3/envs/eyesPY-MPD/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

In [ ]:
# Save the model weights
model_path = "model"
torch.save(model.state_dict(), model_path + '/Modified_Unet_{num_epochs}_epochs.pth')

## To do: 11/6
1. model architecture updates
- get code to work with 256x256 images
- get code to work with mihir eye data
2. Fully labeled data set
3. MRD1 and VPF
- normalize loss function for each metric
- normalize values between 0 and 1

## To do: 11/13:

1. try SAM2 on frames
- make a movie from eye images
- try to segment the eyelid

2. Blink Cycle

3. Percent completeness of blink

4. Even distribution of L/R,

lid function in palsy patients in quantitative ways

## Hyperparameter modifications

1. GMP/ GAP
2. Atrous pooling

# Data engineering

1. diverse eyes
2. different distances